elasticsearchHosts: "https://elasticsearch-master:9200"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: kibana.logging.elk
      paths: 
        - path: /
  tls: []

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: In
            values:
              - "spot"

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"