apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: filebeat-sidecar
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
{{- toYaml .Values.volumeMounts | nindent 10 }}
      - name: {{ .Values.appName }}
        image: {{ .Values.appName }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: {{ .Values.volumeMounts[0].name }}
          mountPath: {{ .Values.volumeMounts[0].mountPath }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      volumes:
      - name: {{ .Values.volumeMounts[0].name }}
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-sidecar-config
          items:
            - key: filebeat.yml
              path: filebeat.yml